version: "3.7"

services:
  traefik:
    image: traefik:2.2
    networks:
      - default
      - traefik
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

  mysql:
    image: mysql:5.7
    networks:
      - default
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  gateway:
    links:
      - mysql:mysql
    depends_on:
      - traefik
      - mysql
    build: .
    container_name: api-gateway
    volumes:
      - .:/api-gateway
      - /api-gateway/node_modules
    restart:
      always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gateway.loadbalancer.server.port=8080"
      - "traefik.http.routers.gateway.rule=Host(`api.brianmatthewsmith.test`)"
      - "traefik.http.routers.gateway.entrypoints=web"
      - "traefik.http.routers.gateway.tls=false"
      - "traefik.http.middlewares.corsHeaders.headers.accesscontrolallowmethods=GET,POST,PUT,PATCH,DELETE,OPTIONS"
      - "traefik.http.middlewares.corsHeaders.headers.accesscontrolallowheaders=Authorization,Origin,Content-Type,Accept"
      - "traefik.http.middlewares.corsHeaders.headers.accesscontrolalloworigin=origin-list-or-null"
      - "traefik.http.middlewares.corsHeaders.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.corsHeaders.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.corsHeaders.headers.addvaryheader=true"
      - "traefik.http.middlewares.corsHeaders.headers.accesscontrolalloworiginlist=http://chat.brianmatthewsmith.test:3000"
      - "traefik.http.routers.gateway.middlewares=corsHeaders"
    networks:
      - default

volumes:
  db_data: {}

networks:
  default:
    driver: bridge
  traefik:
    internal: false
