export const PERMISSION_SUPER_ADMIN = 'SUPER_ADMIN'

export const PERMISSION_PORTFOLIO_ADMIN = 'PORTFOLIO_ADMIN'
export const PERMISSION_PORTFOLIO_USER = 'PORTFOLIO_USER'

export const PERMISSION_CHAT_ADMIN = 'CHAT_ADMIN'
export const PERMISSION_CHAT_USER = 'CHAT_USER'

export const PERMISSION_GAMES_ADMIN = 'GAMES_ADMIN'
export const PERMISSION_GAMES_USER = 'GAMES_USER'

export const PERMISSIONS_ALL = [
  PERMISSION_PORTFOLIO_ADMIN,
  PERMISSION_PORTFOLIO_USER,
  PERMISSION_CHAT_ADMIN,
  PERMISSION_CHAT_USER,
  PERMISSION_GAMES_ADMIN,
  PERMISSION_GAMES_USER
] as const
