http:
  port: ${GATEWAY_PORT:-3001}
  hostname: ${HOSTNAME:-localhost}
apiEndpoints:
  chatAPI:
    host: '*'
    paths: '/chat*'
serviceEndpoints:
  chatService:
    url: 'https://${HOSTNAME:-localhost}:${ROUTING_PORT:-8080}/chat'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  chat:
    apiEndpoints:
      - chatAPI
    policies:
      - cors:
        -
          action:
            credentials: true
            origin: true
            allowedHeaders: ['Accept', Content-Type, 'Cookie']
            methods: 'GET,HEAD,PUT,PATCH,POST,DELETE'
            preflightContinue: false
            optionsSuccessStatus: 204
      - proxy:
          - action:
              serviceEndpoint: chatService
              changeOrigin: true
              stripPath: true
