# name: CI Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm install yarn
    - run: yarn && yarn build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Deploy artifact
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{secrets.SSH_HOST}}
          privateKey: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          dotfiles: true
          local: './build'
          remote: '/var/www/html/api.brianmatthewsmith.com/build'
  scripts:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
          [ -s "$HOME/.nvm/nvm.sh" ] && . "$HOME/.nvm/nvm.sh"
          nvm use 18
          cd /var/www/html/api.brianmatthewsmith.com/build
          yarn
          cd /var/www/html/api.brianmatthewsmith.com
          mkdir temp
          rsync -av --exclude='build' --exclude='temp' --exclude='.env' --remove-source-files /var/www/html/api.brianmatthewsmith.com/ /var/www/html/api.brianmatthewsmith.com/temp/
          find /var/www/html/api.brianmatthewsmith.com -type d -empty -delete
          rsync -av -ur /var/www/html/api.brianmatthewsmith.com/build/ /var/www/html/api.brianmatthewsmith.com/
          rm -rf temp
          rm -rf build
          yarn seed:prod
          pm2 restart api
